from importlib import import_module

from .errors import (
    ArtifactAuthorizationError,
    ArtifactHashMismatchError,
    ArtifactIoError,
    ArtifactNotCommittedError,
    ArtifactNotFoundError,
    ArtifactSchemaMismatchError,
    ArtifactSizeMismatchError,
    ArtifactTooLargeError,
    ArtifactWriteConflictError,
    MessagePublishError,
    MessageTooLargeError,
    RuntimeAzureError,
    RuntimeConfigurationError,
    SerializationError,
)
from .hashing import sha256_bytes, sha256_stream
from .idempotency import step_command_fingerprint
from .json_codec import canonical_json_bytes, decode_json_object
from .models import (
    ARTIFACT_BUNDLE_MEMBERS,
    JSON_MEDIA_TYPE,
    PARQUET_MEDIA_TYPE,
    ArtifactBundle,
    ArtifactBundleWriteReceipt,
    ArtifactCommitEvidence,
    ArtifactFile,
    ArtifactPayload,
    ArtifactReadReceipt,
    ArtifactReadRequest,
    ArtifactReadResult,
    ArtifactWriteReceipt,
    BlobETag,
    ManagedIdentitySettings,
    MaterializedArtifact,
    PublishReceipt,
    ResolvedInputArtifact,
    ResolvedOutputReservation,
    SafeLogContext,
    Sha256Digest,
    StagedArtifactBundleReceipt,
    StagedBlobReceipt,
    TraceContext,
)
from .ports import (
    ArtifactControl,
    ArtifactReader,
    ArtifactReservationBroker,
    ArtifactResolver,
    ArtifactWriter,
    Clock,
    CommandPublisher,
    EventPublisher,
    StructuredLogger,
)
from .problem_mapping import runtime_error_to_problem
from .serialization import (
    MANIFEST_KIND,
    MANIFEST_SCHEMA_ID,
    OUTPUT_LAYOUTS,
    OUTPUT_NAMES,
    OUTPUT_SCHEMA_IDS,
    PARQUET_WRITE_OPTIONS,
    QC_KIND,
    QC_SCHEMA_ID,
    REGISTERED_MATRIX_OUTPUT_NAME,
    ArtifactLayout,
    CanonicalMatrixError,
    CanonicalMatrixResult,
    LayoutField,
    build_canonical_matrix,
    get_layout,
    order_hash,
    serialize_canonical_matrix,
    serialize_harmonization_reports,
    serialize_manifest,
    serialize_qc_sidecars,
    serialize_registration_qc,
)
from .workspace import StepWorkspace

_LAZY_AZURE_EXPORTS = {
    "AzureBlobArtifactReader": ".azure_blob",
    "AzureBlobArtifactWriter": ".azure_blob",
    "CanonicalMatrixBlobArtifactWriter": ".azure_blob",
    "create_blob_service_client": ".azure_clients",
    "create_default_credential": ".azure_clients",
    "create_service_bus_client": ".azure_clients",
    "DEFAULT_MAXIMUM_MESSAGE_BYTES": ".azure_service_bus",
    "AzureServiceBusCommandPublisher": ".azure_service_bus",
    "AzureServiceBusEventPublisher": ".azure_service_bus",
}


def __getattr__(name: str) -> object:
    """Load Azure SDK adapters only when a caller asks for one."""
    module_name = _LAZY_AZURE_EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


__all__ = [
    "ARTIFACT_BUNDLE_MEMBERS",
    "DEFAULT_MAXIMUM_MESSAGE_BYTES",
    "JSON_MEDIA_TYPE",
    "MANIFEST_KIND",
    "MANIFEST_SCHEMA_ID",
    "OUTPUT_LAYOUTS",
    "OUTPUT_NAMES",
    "OUTPUT_SCHEMA_IDS",
    "PARQUET_MEDIA_TYPE",
    "PARQUET_WRITE_OPTIONS",
    "QC_KIND",
    "QC_SCHEMA_ID",
    "REGISTERED_MATRIX_OUTPUT_NAME",
    "ArtifactAuthorizationError",
    "ArtifactBundle",
    "ArtifactBundleWriteReceipt",
    "ArtifactCommitEvidence",
    "ArtifactControl",
    "ArtifactFile",
    "ArtifactHashMismatchError",
    "ArtifactIoError",
    "ArtifactLayout",
    "ArtifactNotCommittedError",
    "ArtifactNotFoundError",
    "ArtifactPayload",
    "ArtifactReadReceipt",
    "ArtifactReadRequest",
    "ArtifactReadResult",
    "ArtifactReader",
    "ArtifactReservationBroker",
    "ArtifactResolver",
    "ArtifactSchemaMismatchError",
    "ArtifactSizeMismatchError",
    "ArtifactTooLargeError",
    "ArtifactWriteConflictError",
    "ArtifactWriteReceipt",
    "ArtifactWriter",
    "AzureBlobArtifactReader",
    "AzureBlobArtifactWriter",
    "AzureServiceBusCommandPublisher",
    "AzureServiceBusEventPublisher",
    "BlobETag",
    "CanonicalMatrixBlobArtifactWriter",
    "CanonicalMatrixError",
    "CanonicalMatrixResult",
    "Clock",
    "CommandPublisher",
    "EventPublisher",
    "LayoutField",
    "ManagedIdentitySettings",
    "MaterializedArtifact",
    "MessagePublishError",
    "MessageTooLargeError",
    "PublishReceipt",
    "ResolvedInputArtifact",
    "ResolvedOutputReservation",
    "RuntimeAzureError",
    "RuntimeConfigurationError",
    "SafeLogContext",
    "SerializationError",
    "Sha256Digest",
    "StagedArtifactBundleReceipt",
    "StagedBlobReceipt",
    "StepWorkspace",
    "StructuredLogger",
    "TraceContext",
    "build_canonical_matrix",
    "canonical_json_bytes",
    "create_blob_service_client",
    "create_default_credential",
    "create_service_bus_client",
    "decode_json_object",
    "get_layout",
    "order_hash",
    "runtime_error_to_problem",
    "serialize_canonical_matrix",
    "serialize_harmonization_reports",
    "serialize_manifest",
    "serialize_qc_sidecars",
    "serialize_registration_qc",
    "sha256_bytes",
    "sha256_stream",
    "step_command_fingerprint",
]
